name: Bilibili Daily Checkin

on:
  schedule:
    - cron: '0 16 * * *'  # 每天0点执行
  workflow_dispatch:  # 支持手动触发

jobs:
  run-bilibili-task:
    runs-on: ubuntu-22.04
    
    steps:
      - uses: actions/checkout@v2
      
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'
          
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests
          
      - name: Run task
        env:
          BILIBILI_COOKIE: ${{ secrets.BILIBILI_COOKIE }}
        run: python auto_task.py